export default {
	build: {
		html: 'public',
		scripts: 'public/assets/js/',
		styles: 'public/assets/css/',
		images: 'public/assets/images/',
		fonts: 'public/assets/fonts/',
		sprites: 'public/assets/images/sprites/',
		svg: 'public/assets/svg/',
		jsons: 'public/assets/jsons/',
		robots: 'public/',
		docs: 'public/docs/',
	},
	public: {
		html: 'public',
		scripts: 'public/assets/js/',
		styles: 'public/assets/css/',
		images: 'public/assets/images/',
		fonts: 'public/assets/fonts/',
		sprites: 'public/assets/images/sprites/',
		svg: 'public/assets/svg/',
		jsons: 'public/assets/jsons/',
		robots: 'public/',
		docs: 'public/docs/',
	},
	src: {
		templates: './src/',
		nunj: 'src/pages/**/*.nunj',
		scripts: 'src/assets/js/index.js',
		styles: 'src/assets/styles/styles.scss',
		images: 'src/assets/images/**/*.*',
		imagesInline: 'src/assets/images/inline/',
		fonts: 'src/assets/fonts/**/*.*',
		sprites: 'src/assets/images/sprites/*.png',
		svg: 'src/assets/svg/**/*.svg',
		jsons: 'src/assets/jsons/**/*.*',
		robots: 'src/assets/robots/**/*.*',
		docs: 'src/assets/docs/**/*.*',
	},
	watch: {
		nunj: ['src/**/*.nunj', 'global-data.json'],
		scripts: 'src/**/*.js',
		styles: 'src/**/*.scss',
		images: 'src/assets/images/**/*.*',
		fonts: 'src/assets/fonts/**/*.*',
		sprites: 'src/assets/images/sprites/*.png',
		svg: 'src/assets/svg/**/*.svg',
		jsons: 'src/assets/jsons/**/*.json',
		robots: 'src/assets/robots/**/*.*',
		docs: 'src/assets/docs/**/*.*',
	},
	clean: 'build/',
};
